use_frameworks!
workspace 'IDOBlue'
source 'https://github.com/idoosmart/IDOSmartSpec.git'
platform :ios, '13.0'
target 'IDOBlue' do
#   pod 'IDOBluetooth', '3.13.32'
#   pod 'IDOBlueProtocol', '3.40.52'
#   pod 'IDOBlueUpdate', '3.6.25'

   pod 'IDOBluetooth'
   pod 'IDOBlueProtocol'
   pod 'IDOBlueUpdate'
end
