use_frameworks!
workspace 'IDOBlue'
source 'https://github.com/idoosmart/IDOSmartSpec.git'
platform :ios, '9.0'
target 'IDOBlue' do
   pod 'IDOBluetooth'
   pod 'IDOBlueProtocol'
   pod 'IDOBlueUpdate'
end
